force-app/main/default/objects/OpenAI_Chat__c/OpenAI_Chat__c.object-meta.xml
<CustomObject>
    <label>OpenAI Chat</label>
    <nameField>
        <displayFormat>OAI-C-{0000}</displayFormat>
        <label>OpenAI Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpenAI Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpenAI_Chat__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>The chat model to talk with</inlineHelpText>
    <label>Model</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpenAI_Chat_Message__c/OpenAI_Chat_Message__c.object-meta.xml
<CustomObject>
    <label>OpenAI Chat Message</label>
    <nameField>
        <displayFormat>OAI-CM-{0000}</displayFormat>
        <label>OpenAI Chat Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpenAI Chat Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpenAI_Chat_Message__c/fields/Input_Message__c.field-meta.xml
<CustomField>
    <fullName>Input_Message__c</fullName>
    <label>Input Message</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpenAI_Chat_Message__c/fields/OpenAI_Chat__c.field-meta.xml
<CustomField>
    <fullName>OpenAI_Chat__c</fullName>
    <label>OpenAI Chat</label>
    <referenceTo>OpenAI_Chat__c</referenceTo>
    <relationshipLabel>OpenAI Chat Messages</relationshipLabel>
    <relationshipName>OpenAI_Chat_Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpenAI_Chat_Message__c/fields/Output_Message__c.field-meta.xml
<CustomField>
    <fullName>Output_Message__c</fullName>
    <label>Output Message</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpenAI_Event__e/OpenAI_Event__e.object-meta.xml
<CustomObject>
    <description>Used for Pub-Sub model on LWC because the API response can take some time to process</description>
    <label>OpenAI Event</label>
    <pluralLabel>OpenAI Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpenAI_Event__e/fields/Chat_Id__c.field-meta.xml
<CustomField>
    <fullName>Chat_Id__c</fullName>
    <description>The Id of a parent chat that has had a response from OpenAI</description>
    <label>Chat Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpenAI_Event__e/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether an error occurred during the event</description>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpenAI_Event__e/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>Used to identify user who is part of the chat so that pub-sub only refreshes their experience</description>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpenAI_Setting__mdt/OpenAI_Setting__mdt.object-meta.xml
<CustomObject>
    <label>OpenAI Setting</label>
    <pluralLabel>OpenAI Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpenAI_Setting__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <inlineHelpText>The endpoint to interact with</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpenAI_Setting__mdt/fields/model__c.field-meta.xml
<CustomField>
    <fullName>model__c</fullName>
    <inlineHelpText>The model to use for the endpoint</inlineHelpText>
    <label>model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpenAiChatController.cls
/**
 * @description       : Used to handle the OpenAI Chat API callout and to create new chats and retrieve existing chats.
 *                    : This class is used by the OpenAIChat Lightning Web Component.
 * @author            : Jared Simpson
 * @group             : Loosely Canon LLC
 * @last modified on  : 07-05-2023
 * @last modified by  : Jared Simpson
**/
public with sharing class OpenAiChatController {
    private static OpenAI_Setting__mdt chatSetting = OpenAI_Setting__mdt.getInstance('Chat_Completions_v1');

    /**
    * @description 
    * @author Jared Simpson | 06-16-2023 
    * @param userInput 
    * @param chatId 
    * @return String 
    **/
    @AuraEnabled
    public static String chatWithOpenAI(String userInput, String chatId) {
        try{
            // chatWithOpenAiCallout(UserInfo.getUserId(), userInput, chatId);
            // return 'Chat is running in the background.';
            String result = chatHandler(userInput, chatId);
            return result;
        } catch (Exception e) {
            chatWithOpenAiCallout(UserInfo.getUserId(), userInput, chatId);
            return 'It is taking longer than expected to get a response from OpenAI. The chat will continue to run in the background.';
        }
        
    }

    /**
    * @description Input parameter wrapper class for the invocable method.
    **/
    public class ChatParams {
        @InvocableVariable(label='User Input' required=true)
        public String userInput;

        @InvocableVariable(label='Chat Id' required=true)
        public String chatId;
    }

    /**
    * @description Invocable method for Salesforce flows to call the chatWithOpenAI method.
    **/
    @InvocableMethod(label='Chat with OpenAI')
    public static List<String> invokeChatWithOpenAI(List<ChatParams> paramsList) {
        List<String> results = new List<String>();

        for (ChatParams params : paramsList) {
            String result = chatWithOpenAI(params.userInput, params.chatId);
            results.add(result);
        }

        return results;
    }


    @future(callout=true)
    public static void chatWithOpenAiCallout(Id userId, String userInput, String chatId) {
        // Create an instance of the platform event
        OpenAI_Event__e event = new OpenAI_Event__e();
        event.User_Id__c = userId;
        event.Chat_Id__c = chatId;
        event.Error__c = false;

        try{
            String response = chatHandler(userInput, chatId);
            Database.SaveResult result = EventBus.publish(event);
        } catch (Exception e) {
            System.debug('Error on chatWithOpenAiCallout: ' + e.getMessage());
            event.Error__c = true;
            Database.SaveResult result = EventBus.publish(event);
        }

    }

    private static String chatHandler(String userInput, String chatId){
        OpenAI_Chat_Message__c[] chatMessages = [SELECT Id, Input_Message__c, Output_Message__c 
            FROM OpenAI_Chat_Message__c WITH_SECURITY_ENFORCED WHERE OpenAI_Chat__c = :chatId ORDER BY CreatedDate ASC];
    
        if(chatMessages.size() > 0 && (!Utilities.checkCreateFieldLevelSecurity(chatMessages[0]) || !Utilities.checkUpdateFieldLevelSecurity(chatMessages[0]))) {
            return 'Error: You do not have access to the OpenAI Chat Messages.';
        }

        List<Messages> messages = new List<Messages>();
        for(OpenAI_Chat_Message__c m : chatMessages){
            Messages message = new Messages();
            message.content = m.Input_Message__c != null ? m.Input_Message__c : m.Output_Message__c;
            message.role = m.Input_Message__c != null ? 'user' : 'assistant';
            messages.add(message);
        }

        Messages message = new Messages();
        message.role = 'user';
        message.content = userInput;
        messages.add(message);

        OpenAI_Chat_Message__c newInputChat = new OpenAI_Chat_Message__c(
            Input_Message__c = userInput,
            OpenAI_Chat__c = chatId
        );


        ChatWrapper inputChatWrapper = new ChatWrapper();
        inputChatWrapper.model = chatSetting.model__c;
        inputChatWrapper.messages = messages;

        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:OpenAI_API/'+chatSetting.Endpoint__c);
        req.setMethod('POST');
        req.setBody(JSON.serialize(inputChatWrapper));
        if(System.isFuture() || System.isBatch() || System.isQueueable()){
            req.setTimeout(120000);
        }

        HttpResponse res = new Http().send(req);

        try{
            Database.SaveResult sr = Database.insert(newInputChat);
        }
        catch(Exception e){
            System.debug('Error on insert of input chat: ' + e.getMessage());
        }

        OpenAiChatWrapper chatWrapper = OpenAiChatWrapper.parse(res.getBody());

        OpenAI_Chat_Message__c newOutputChat = new OpenAI_Chat_Message__c(
            Output_Message__c = chatWrapper.choices[0].message.content,
            OpenAI_Chat__c = chatId
        );

        try {
            Database.SaveResult sr = Database.insert(newOutputChat);
        } catch (Exception e) {
            System.debug('Error on insert of output chat: ' + e.getMessage());
        }

        chatMessages = [SELECT Id, Input_Message__c, Output_Message__c 
            FROM OpenAI_Chat_Message__c WITH_SECURITY_ENFORCED WHERE OpenAI_Chat__c = :chatId ORDER BY CreatedDate ASC];
        
        return JSON.serialize(chatMessages);
    }

    /**
    * @description 
    * @author Jared Simpson | 06-16-2023 
    * @return List<OpenAI_Chat__c> 
    **/
    @AuraEnabled(cacheable=false)
    public static List<OpenAI_Chat__c> getLastChats() {
        // Retrieves the last 10 chats the current user created
        return [SELECT Id, Name FROM OpenAI_Chat__c WITH_SECURITY_ENFORCED WHERE CreatedBy.Id = :UserInfo.getUserId() ORDER BY CreatedDate DESC LIMIT 10];
    }

    /**
    * @description 
    * @author Jared Simpson | 06-16-2023 
    * @return String 
    **/
    @AuraEnabled(cacheable=false)
    public static String createNewChat() {
        OpenAI_Chat__c newChat = new OpenAI_Chat__c(model__c=chatSetting.model__c);
        insert newChat;
        return newChat.Id;
    }

    /**
    * @description 
    * @author Jared Simpson | 06-16-2023 
    * @param chatId 
    * @return string 
    **/
    @AuraEnabled(cacheable=false)
    public static string getExistingMessages(String chatId){
        try {
            OpenAI_Chat_Message__c[] chatMessages = [SELECT Id, Input_Message__c, Output_Message__c 
            FROM OpenAI_Chat_Message__c WITH_SECURITY_ENFORCED WHERE OpenAI_Chat__c = :chatId ORDER BY CreatedDate ASC];
            return JSON.serialize(chatMessages);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * @description Used to wrap the response from the OpenAI API callout. This is needed to simplify JSON deserialization
    * @author Jared Simpson | 06-16-2023 
    **/
    public class ChatWrapper{
        public String model;
        public Messages[] messages;
    }

    /**
    * @description Used to wrap the response from the OpenAI API callout. This is needed to simplify JSON deserialization
    * @author Jared Simpson | 06-16-2023 
    **/
    public class Messages {
        public String role;
        public String content;
    } 
}